version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /opt/offer_catalog/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PSW}
    ports:
      - ${POSTGRES_PORT}:5432

  offer_catalog:
    container_name: offer_catalog
    image: offer_catalog:latest
    restart: always
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    environment:
      OFFER_CATALOG_HOSTNAME: ${OFFER_CATALOG_HOSTNAME}
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_MODE: ${POSTGRES_MODE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PSW: ${POSTGRES_PSW}
      KAFKA_BOOTSTRAP_ADDRESS: ${KAFKA_BOOTSTRAP_ADDRESS}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      DID_SERVICE_HOSTNAME: ${DID_SERVICE_HOSTNAME}
      DID_SERVICE_PORT: ${DID_SERVICE_PORT}
      DID_SERVICE_REQUEST_PATH: ${DID_SERVICE_REQUEST_PATH}
      SC_LCM_HOSTNAME: ${SC_LCM_HOSTNAME}
      SC_LCM_PORT: ${SC_LCM_PORT}
      SC_LCM_PRODUCT_OFFER_REQUEST_PATH: ${SC_LCM_PRODUCT_OFFER_REQUEST_PATH}
      SC_LCM_PRODUCT_ORDER_REQUEST_PATH: ${SC_LCM_PRODUCT_ORDER_REQUEST_PATH}
      SC_LCM_DERIVATIVE_ISSUE_REQUEST_PATH: ${SC_LCM_DERIVATIVE_ISSUE_REQUEST_PATH}
      SC_LCM_SLA_REQUEST_PATH: ${SC_LCM_SLA_REQUEST_PATH}
      SKIP_SC_LCM_POST: ${SKIP_SC_LCM_POST}
      SRSD_HOSTNAME: ${SRSD_HOSTNAME}
      SRSD_PORT: ${SRSD_PORT}
      SRSD_REQUEST_PATH: ${SRSD_REQUEST_PATH}
      SKIP_SRSD_POST: ${SKIP_SRSD_POST}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24