version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /opt/offer_catalog/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - ${POSTGRES_PORT}:5432

  offer_catalog:
    container_name: offer_catalog
    image: offer_catalog:latest
    restart: always
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    environment:
      OFFER_CATALOG_HOSTNAME: ${OFFER_CATALOG_HOSTNAME}
      OFFER_CATALOG_PORT: ${OFFER_CATALOG_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_MODE: ${POSTGRES_MODE}
      KAFKA_BOOTSTRAP_ADDRESS: ${KAFKA_BOOTSTRAP_ADDRESS}
      DID_SERVICE_HOSTNAME: ${DID_SERVICE_HOSTNAME}
      DID_SERVICE_PORT: ${DID_SERVICE_PORT}
      DID_SERVICE_REQUEST_PATH: ${DID_SERVICE_REQUEST_PATH}
      SC_LCM_HOSTNAME: ${SC_LCM_HOSTNAME}
      SC_LCM_PORT: ${SC_LCM_PORT}
      SC_LCM_REQUEST_PATH: ${SC_LCM_REQUEST_PATH}
      SRSD_HOSTNAME: ${SRSD_HOSTNAME}
      SRSD_PORT: ${SRSD_PORT}
      SRSD_REQUEST_PATH: ${SRSD_REQUEST_PATH}
    ports:
      - ${OFFER_CATALOG_PORT}:${OFFER_CATALOG_PORT}
    depends_on:
      - postgres

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24